// ─────────────────────────────────────────────────────────────────────────────
// HOW TO USE THIS FILE:
// Call CompetitionSeeder.seedIfEmpty() once when the app starts (in main.dart)
// or add a button in your dev/debug screen.
// It only seeds if the competitions collection is empty.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';

class CompetitionSeeder {
  static Future<void> seedIfEmpty() async {
    final firestore = FirebaseFirestore.instance;
    final snapshot = await firestore.collection('competitions').limit(1).get();

    if (snapshot.docs.isNotEmpty) return; // already seeded

    final batch = firestore.batch();

    for (final comp in competitions) {
      final ref = firestore.collection('competitions').doc();
      batch.set(ref, comp);
    }

    await batch.commit();
    debugPrint('Competitions seeded successfully');
  }

  static final List<Map<String, dynamic>> competitions = [
    // ── AI / Tech ────────────────────────────────────────────────────────────
    {
      'title': 'Google Solution Challenge',
      'organizer': 'Google',
      'field': 'AI / Tech',
      'major_tags': ['Computer Science', 'Software Engineering', 'AI'],
      'skill_tags': [
        'machine learning',
        'web development',
        'mobile development',
        'problem solving',
      ],
      'deadline': '2025-03-31',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://developers.google.com/community/gdsc/solution-challenge',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Microsoft Imagine Cup',
      'organizer': 'Microsoft',
      'field': 'AI / Tech',
      'major_tags': ['Computer Science', 'Software Engineering', 'AI'],
      'skill_tags': ['AI', 'cloud computing', 'app development', 'IoT'],
      'deadline': '2025-02-28',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://imaginecup.microsoft.com',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'AWS DeepRacer Student',
      'organizer': 'Amazon Web Services',
      'field': 'AI / Tech',
      'major_tags': ['Computer Science', 'AI', 'Data Science'],
      'skill_tags': ['reinforcement learning', 'machine learning', 'Python'],
      'deadline': '2025-06-30',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://student.deepracer.com',
      'difficulty_level': 'Beginner',
      'team_allowed': false,
    },
    {
      'title': 'Kaggle Competitions',
      'organizer': 'Kaggle / Google',
      'field': 'Data Science',
      'major_tags': ['Computer Science', 'Data Science', 'Statistics'],
      'skill_tags': [
        'machine learning',
        'data analysis',
        'Python',
        'statistics',
      ],
      'deadline': '2025-12-31',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.kaggle.com/competitions',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Meta Hacker Cup',
      'organizer': 'Meta',
      'field': 'AI / Tech',
      'major_tags': ['Computer Science'],
      'skill_tags': [
        'algorithms',
        'competitive programming',
        'data structures',
      ],
      'deadline': '2025-08-01',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.facebook.com/codingcompetitions/hacker-cup',
      'difficulty_level': 'Advanced',
      'team_allowed': false,
    },
    {
      'title': 'ICPC — International Collegiate Programming Contest',
      'organizer': 'ICPC Foundation',
      'field': 'AI / Tech',
      'major_tags': ['Computer Science'],
      'skill_tags': [
        'algorithms',
        'data structures',
        'competitive programming',
      ],
      'deadline': '2025-09-15',
      'location_type': 'In-Person',
      'country': 'Regional/Global',
      'url': 'https://icpc.global',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'NASA Space Apps Challenge',
      'organizer': 'NASA',
      'field': 'Science / Engineering',
      'major_tags': [
        'Computer Science',
        'Engineering',
        'Physics',
        'Data Science',
      ],
      'skill_tags': [
        'data analysis',
        'space science',
        'programming',
        'geospatial',
      ],
      'deadline': '2025-10-05',
      'location_type': 'Hybrid',
      'country': 'Global',
      'url': 'https://www.spaceappschallenge.org',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Business / Entrepreneurship ───────────────────────────────────────────
    {
      'title': 'Hult Prize',
      'organizer': 'Hult Prize Foundation',
      'field': 'Entrepreneurship',
      'major_tags': [
        'Business',
        'Engineering',
        'Computer Science',
        'Design',
        'Health',
      ],
      'skill_tags': [
        'business planning',
        'social entrepreneurship',
        'pitching',
        'teamwork',
      ],
      'deadline': '2025-02-01',
      'location_type': 'Hybrid',
      'country': 'Global',
      'url': 'https://www.hultprize.org',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Injaz Arab Young Entrepreneurs Competition',
      'organizer': 'Injaz Arab',
      'field': 'Entrepreneurship',
      'major_tags': ['Business', 'Marketing', 'Finance'],
      'skill_tags': [
        'business model',
        'entrepreneurship',
        'pitching',
        'market research',
      ],
      'deadline': '2025-03-15',
      'location_type': 'In-Person',
      'country': 'MENA',
      'url': 'https://www.injazarab.org',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },
    {
      'title': 'MIT \$100K Entrepreneurship Competition',
      'organizer': 'MIT',
      'field': 'Entrepreneurship',
      'major_tags': ['Business', 'Engineering', 'Science', 'Computer Science'],
      'skill_tags': [
        'startup',
        'pitching',
        'business plan',
        'product development',
      ],
      'deadline': '2025-04-01',
      'location_type': 'Hybrid',
      'country': 'Global',
      'url': 'https://www.mit100k.org',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'Arab Startup Competition',
      'organizer': 'ArabNet',
      'field': 'Entrepreneurship',
      'major_tags': ['Business', 'Computer Science', 'Marketing'],
      'skill_tags': [
        'startup pitch',
        'MVP',
        'product development',
        'business model',
      ],
      'deadline': '2025-05-10',
      'location_type': 'Hybrid',
      'country': 'MENA',
      'url': 'https://www.arabnet.me/competitions',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'ENACTUS World Cup',
      'organizer': 'Enactus',
      'field': 'Entrepreneurship',
      'major_tags': ['Business', 'Social Sciences', 'Engineering'],
      'skill_tags': [
        'social entrepreneurship',
        'project management',
        'community impact',
      ],
      'deadline': '2025-09-20',
      'location_type': 'In-Person',
      'country': 'Global',
      'url': 'https://enactus.org/competition/world-cup',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Finance ───────────────────────────────────────────────────────────────
    {
      'title': 'CFA Institute Research Challenge',
      'organizer': 'CFA Institute',
      'field': 'Finance',
      'major_tags': ['Finance', 'Accounting', 'Economics'],
      'skill_tags': [
        'financial analysis',
        'equity research',
        'valuation',
        'report writing',
      ],
      'deadline': '2025-01-31',
      'location_type': 'In-Person',
      'country': 'Global',
      'url': 'https://www.cfainstitute.org/en/research/research-challenge',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'Bloomberg Global Trading Challenge',
      'organizer': 'Bloomberg',
      'field': 'Finance',
      'major_tags': ['Finance', 'Economics', 'Business'],
      'skill_tags': [
        'trading',
        'financial markets',
        'portfolio management',
        'risk',
      ],
      'deadline': '2025-04-30',
      'location_type': 'Online',
      'country': 'Global',
      'url':
          'https://www.bloomberg.com/company/values/tech-at-bloomberg/bloomberg-global-trading-challenge',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'MENA Fintech Association Hackathon',
      'organizer': 'MENA Fintech Association',
      'field': 'Finance / Tech',
      'major_tags': ['Finance', 'Computer Science', 'Business'],
      'skill_tags': [
        'fintech',
        'app development',
        'financial innovation',
        'API',
      ],
      'deadline': '2025-07-20',
      'location_type': 'Hybrid',
      'country': 'MENA',
      'url': 'https://menafintechassociation.com',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Design ────────────────────────────────────────────────────────────────
    {
      'title': 'Adobe Design Achievement Awards',
      'organizer': 'Adobe',
      'field': 'Design',
      'major_tags': ['Design', 'Animation', 'Fine Arts', 'Architecture'],
      'skill_tags': [
        'graphic design',
        'UX/UI',
        'photography',
        'video',
        'illustration',
      ],
      'deadline': '2025-05-31',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.behance.net/adaa',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'UX Design Challenge by Figma',
      'organizer': 'Figma',
      'field': 'Design / Tech',
      'major_tags': ['Design', 'Computer Science', 'UX'],
      'skill_tags': ['UX design', 'prototyping', 'user research', 'Figma'],
      'deadline': '2025-03-01',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.figma.com/community/challenge',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },
    {
      'title': 'Red Dot Design Award — Concept',
      'organizer': 'Red Dot',
      'field': 'Design',
      'major_tags': ['Design', 'Engineering', 'Architecture'],
      'skill_tags': [
        'product design',
        'concept design',
        'innovation',
        'prototyping',
      ],
      'deadline': '2025-06-01',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.red-dot.org/competition/red-dot-design-award',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'D&AD New Blood Awards',
      'organizer': 'D&AD',
      'field': 'Design / Marketing',
      'major_tags': ['Design', 'Marketing', 'Advertising', 'Media'],
      'skill_tags': [
        'branding',
        'advertising',
        'graphic design',
        'copywriting',
      ],
      'deadline': '2025-04-10',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.dandad.org/en/d-ad-new-blood-awards',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Marketing ─────────────────────────────────────────────────────────────
    {
      'title': 'Cannes Lions Young Lions',
      'organizer': 'Cannes Lions',
      'field': 'Marketing / Design',
      'major_tags': ['Marketing', 'Design', 'Media'],
      'skill_tags': [
        'advertising',
        'creative strategy',
        'visual design',
        'copywriting',
      ],
      'deadline': '2025-04-15',
      'location_type': 'In-Person',
      'country': 'Global',
      'url': 'https://www.canneslions.com/young-lions',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'Google Online Marketing Challenge',
      'organizer': 'Google',
      'field': 'Marketing / Tech',
      'major_tags': ['Marketing', 'Business', 'Computer Science'],
      'skill_tags': [
        'Google Ads',
        'digital marketing',
        'analytics',
        'campaign management',
      ],
      'deadline': '2025-05-15',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://digitalmarketingchallenge.withgoogle.com',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },

    // ── Engineering ───────────────────────────────────────────────────────────
    {
      'title': 'Formula SAE / Formula Student',
      'organizer': 'SAE International',
      'field': 'Engineering',
      'major_tags': [
        'Mechanical Engineering',
        'Electrical Engineering',
        'Industrial Engineering',
      ],
      'skill_tags': [
        'mechanical design',
        'CAD',
        'manufacturing',
        'teamwork',
        'project management',
      ],
      'deadline': '2025-06-20',
      'location_type': 'In-Person',
      'country': 'Global',
      'url': 'https://www.sae.org/attend/student-events/formula-sae-michigan',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'Shell Eco-Marathon',
      'organizer': 'Shell',
      'field': 'Engineering',
      'major_tags': [
        'Mechanical Engineering',
        'Electrical Engineering',
        'Environmental Engineering',
      ],
      'skill_tags': [
        'fuel efficiency',
        'vehicle design',
        'energy',
        'sustainability',
      ],
      'deadline': '2025-05-08',
      'location_type': 'In-Person',
      'country': 'Regional',
      'url':
          'https://www.shell.com/energy-and-innovation/shell-ecomarathon.html',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'Jordan Engineering Association Student Award',
      'organizer': 'JEA',
      'field': 'Engineering',
      'major_tags': [
        'Civil Engineering',
        'Mechanical Engineering',
        'Electrical Engineering',
      ],
      'skill_tags': [
        'project design',
        'engineering analysis',
        'sustainability',
        'innovation',
      ],
      'deadline': '2025-04-25',
      'location_type': 'In-Person',
      'country': 'Jordan',
      'url': 'https://www.jea.org.jo',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Health / Science ──────────────────────────────────────────────────────
    {
      'title': 'iGEM — International Genetically Engineered Machine',
      'organizer': 'iGEM Foundation',
      'field': 'Science / Health',
      'major_tags': [
        'Biology',
        'Biomedical Engineering',
        'Biotechnology',
        'Chemistry',
      ],
      'skill_tags': [
        'synthetic biology',
        'lab skills',
        'research',
        'scientific writing',
      ],
      'deadline': '2025-10-15',
      'location_type': 'In-Person',
      'country': 'Global',
      'url': 'https://igem.org',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'WHO Global Health Challenge',
      'organizer': 'World Health Organization',
      'field': 'Health',
      'major_tags': ['Public Health', 'Medicine', 'Nursing', 'Biology'],
      'skill_tags': [
        'public health',
        'health policy',
        'data analysis',
        'communication',
      ],
      'deadline': '2025-09-01',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.who.int/activities/fostering-innovation',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Arab Health Innovation Award',
      'organizer': 'Arab Health',
      'field': 'Health / Tech',
      'major_tags': [
        'Medicine',
        'Biomedical Engineering',
        'Computer Science',
        'Pharmacy',
      ],
      'skill_tags': [
        'health tech',
        'innovation',
        'medical devices',
        'AI in health',
      ],
      'deadline': '2025-01-28',
      'location_type': 'In-Person',
      'country': 'MENA',
      'url': 'https://www.arabhealthonline.com',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Open Innovation / Sustainability ──────────────────────────────────────
    {
      'title': 'UN SDG Action Awards',
      'organizer': 'United Nations',
      'field': 'Open Innovation',
      'major_tags': ['Any Major'],
      'skill_tags': [
        'sustainability',
        'social impact',
        'innovation',
        'project management',
      ],
      'deadline': '2025-07-31',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://sdgactionawards.org',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },
    {
      'title': 'Climate Launchpad',
      'organizer': 'Climate-KIC',
      'field': 'Sustainability / Entrepreneurship',
      'major_tags': [
        'Environmental Engineering',
        'Business',
        'Science',
        'Computer Science',
      ],
      'skill_tags': [
        'green innovation',
        'cleantech',
        'pitching',
        'sustainability',
      ],
      'deadline': '2025-06-01',
      'location_type': 'Hybrid',
      'country': 'Global',
      'url': 'https://climatelaunchpad.org',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Zain Innovation Campus (ZINC)',
      'organizer': 'Zain Jordan',
      'field': 'Open Innovation / Tech',
      'major_tags': ['Computer Science', 'Business', 'Design', 'Engineering'],
      'skill_tags': [
        'tech innovation',
        'mobile apps',
        'AI',
        'entrepreneurship',
        'UX',
      ],
      'deadline': '2025-05-30',
      'location_type': 'In-Person',
      'country': 'Jordan/Palestine',
      'url': 'https://zinc.jo',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Fikra Challenge — Palestinian Youth Fund',
      'organizer': 'Palestinian Youth Fund',
      'field': 'Open Innovation',
      'major_tags': ['Any Major'],
      'skill_tags': [
        'social innovation',
        'community development',
        'leadership',
        'project planning',
      ],
      'deadline': '2025-03-25',
      'location_type': 'Hybrid',
      'country': 'Palestine',
      'url': 'https://palestinianyouthfund.org',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },
    {
      'title': 'King Abdullah II Award for Youth Innovation',
      'organizer': 'King Abdullah II Fund',
      'field': 'Open Innovation / Tech',
      'major_tags': ['Any Major'],
      'skill_tags': ['innovation', 'technology', 'leadership', 'social impact'],
      'deadline': '2025-08-15',
      'location_type': 'In-Person',
      'country': 'Jordan',
      'url': 'https://kafd.gov.jo',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Arab Youth Climate Movement Challenge',
      'organizer': 'AYCM',
      'field': 'Sustainability',
      'major_tags': [
        'Environmental Science',
        'Business',
        'Engineering',
        'Social Sciences',
      ],
      'skill_tags': [
        'climate action',
        'community projects',
        'advocacy',
        'leadership',
      ],
      'deadline': '2025-04-20',
      'location_type': 'Hybrid',
      'country': 'MENA',
      'url': 'https://www.arabyouthclimate.org',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },

    // ── Jordan / Palestine local ───────────────────────────────────────────────
    {
      'title': 'Gaza Sky Geeks Startup Cup',
      'organizer': 'Gaza Sky Geeks',
      'field': 'Entrepreneurship / Tech',
      'major_tags': ['Computer Science', 'Business', 'Design'],
      'skill_tags': [
        'startup',
        'product development',
        'pitching',
        'user research',
      ],
      'deadline': '2025-06-10',
      'location_type': 'Hybrid',
      'country': 'Palestine',
      'url': 'https://gazaskygeeks.com',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'INJAZ Palestine Business Leader Program',
      'organizer': 'INJAZ Palestine',
      'field': 'Business / Leadership',
      'major_tags': ['Business', 'Marketing', 'Finance', 'Management'],
      'skill_tags': [
        'leadership',
        'business skills',
        'communication',
        'teamwork',
      ],
      'deadline': '2025-03-20',
      'location_type': 'In-Person',
      'country': 'Palestine',
      'url': 'https://injaz-palestine.org',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },
    {
      'title': 'Jordanian University Innovation Competition',
      'organizer': 'Higher Education Accreditation Commission',
      'field': 'Open Innovation',
      'major_tags': ['Any Major'],
      'skill_tags': [
        'research',
        'innovation',
        'prototype',
        'project presentation',
      ],
      'deadline': '2025-04-10',
      'location_type': 'In-Person',
      'country': 'Jordan',
      'url': 'https://heac.gov.jo',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },
    {
      'title': 'Arab Innovation Academy',
      'organizer': 'Qatar Foundation',
      'field': 'Open Innovation',
      'major_tags': ['Any Major'],
      'skill_tags': [
        'design thinking',
        'innovation',
        'collaboration',
        'social entrepreneurship',
      ],
      'deadline': '2025-07-01',
      'location_type': 'In-Person',
      'country': 'MENA',
      'url': 'https://arabinnovationacademy.com',
      'difficulty_level': 'Intermediate',
      'team_allowed': true,
    },

    // ── Law / Social Sciences ─────────────────────────────────────────────────
    {
      'title': 'Model United Nations (MUN)',
      'organizer': 'Various Organizers',
      'field': 'Social Sciences / Law',
      'major_tags': [
        'Political Science',
        'Law',
        'International Relations',
        'Any Major',
      ],
      'skill_tags': [
        'public speaking',
        'debate',
        'diplomacy',
        'research',
        'resolution writing',
      ],
      'deadline': '2025-12-01',
      'location_type': 'In-Person',
      'country': 'Global/Regional',
      'url': 'https://www.un.org/en/mun',
      'difficulty_level': 'Beginner',
      'team_allowed': true,
    },
    {
      'title': 'Philip C. Jessup International Law Moot Court',
      'organizer': 'ILSA',
      'field': 'Law',
      'major_tags': ['Law'],
      'skill_tags': [
        'international law',
        'oral argumentation',
        'legal writing',
        'research',
      ],
      'deadline': '2025-01-31',
      'location_type': 'In-Person',
      'country': 'Global',
      'url': 'https://www.ilsa.org/jessup',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },

    // ── Architecture / Media ──────────────────────────────────────────────────
    {
      'title': 'Archiprix International',
      'organizer': 'Archiprix',
      'field': 'Architecture',
      'major_tags': ['Architecture', 'Urban Planning', 'Design'],
      'skill_tags': [
        'architectural design',
        'urban planning',
        'sustainability',
        'presentation',
      ],
      'deadline': '2025-03-01',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://www.archiprix.org',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
    {
      'title': 'Youth Journalism International Competition',
      'organizer': 'YJI',
      'field': 'Media / Journalism',
      'major_tags': ['Media', 'Communications', 'Journalism', 'English'],
      'skill_tags': [
        'news writing',
        'photography',
        'reporting',
        'storytelling',
      ],
      'deadline': '2025-05-01',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://youthjournalism.org',
      'difficulty_level': 'Beginner',
      'team_allowed': false,
    },
    {
      'title': 'IEEE Xtreme Programming Competition',
      'organizer': 'IEEE',
      'field': 'AI / Tech',
      'major_tags': ['Computer Science', 'Software Engineering'],
      'skill_tags': ['competitive programming', 'algorithms', 'mathematics'],
      'deadline': '2025-10-25',
      'location_type': 'Online',
      'country': 'Global',
      'url': 'https://ieeextreme.org',
      'difficulty_level': 'Advanced',
      'team_allowed': true,
    },
  ];
}
